from fastapi import FastAPI
from utils import parse_schema, parse_gemini_response #,translate_to_sql
from db_connection import DBConnection, DBConnectionAPI
from inputs import QueryInput, LanguageInput, TokensInput, DBInput
from ai_models import HuggingFaceModel, GoogleModel
from translate_language import TranslateLanguage
from language_config import LanguageConfig
from utils import count_tokens_in_string, identify_tables_in_query, identify_columns_in_query
from fastapi.middleware.cors import CORSMiddleware
from fastapi import HTTPException, status

app = FastAPI()

origins = [
    "localhost:8081",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

#db_schema = """
#   "stadium" "Stadium_ID" int , "Location" text , "Name" text , "Capacity" int , "Highest" int , "Lowest" int , "Average" int , foreign_key:  primary key: "Stadium_ID" [SEP] "singer" "Singer_ID" int , "Name" text , "Country" text , "Song_Name" text , "Song_release_year" text , "Age" int , "Is_male" bool , foreign_key:  primary key: "Singer_ID" [SEP] "concert" "concert_ID" int , "concert_Name" text , "Theme" text , "Year" text , foreign_key: "Stadium_ID" text from "stadium" "Stadium_ID" , primary key: "concert_ID" [SEP] "singer_in_concert"  foreign_key: "concert_ID" int from "concert" "concert_ID" , "Singer_ID" text from "singer" "Singer_ID" , primary key: "concert_ID" "Singer_ID"
#"""

configurated_language = LanguageConfig()

db = DBConnectionAPI(db_host=None, db_name=None, db_password=None, db_user=None)

"""
Obtain the database schema in the required format
"""
db_schema = db.get_db_schema()

@app.get("/")
def read_root():
    return {"message": "Hello, I am your sql assistant"}


"""
This endpoint calls to Huggin Face model and return the query in SQL sintax
Params: input_data = Natural language query
Return: Json with the SQL Query generated by the Huggin Face model = { sql_query: SELECT ... FROM ... WHERE ... }
"""
@app.post("/t5/translate/")
async def translate_to_sql(input_data: QueryInput):
    try:
        selected_language = await get_language()
        db_schema = db.get_db_schema()
        if selected_language.get('language') == "Español":
            nl_query = input_data.query
            translator = TranslateLanguage()
            translated_nl_query = translator.translate_to_english(nl_query)
            input_text = " ".join(["Question: ",translated_nl_query, "Schema:", db_schema])
        else:
            nl_query = input_data.query
            input_text = " ".join(["Question: ",nl_query, "Schema:", db_schema])
        init_model = HuggingFaceModel()
        #print("input text: ", input_text)
        response = init_model.call_translate_model(input_text=input_text)
        return {"sql_query": response}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")
    
    
"""
This endpoint execute the SQL query generated by the Huggin Face model
Params: input_data = Natural language query
Return: Json with the results of the SQL query generated by Huggin Face model from the natural language query
        {query_result: [(result_1_column_1_value, ..., result_1_column_n_value), ..., (result_n_column_1_value, ..., result_n_column_n_value)]}
"""
@app.post("/t5/execute_query/")
async def execute_query(input_data: QueryInput):
    try:
       sql_query = await translate_to_sql(input_data)
       print(sql_query)
       #db = DBConnection()
       db.generate_db_connection()
       cursor = db.get_db_cursor()
       cursor.execute(f"""
           {sql_query.get('sql_query')}
        """)
       query_result = cursor.fetchall()
       db.quit_db_connection()
       return {"query_result": query_result, "columns": identify_columns_in_query(sql_query.get('sql_query'))}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")

"""
This endpoint calls to Google Gemini model and return the query in SQL sintax
Params: input_data = Natural language query
Return: Json with the SQL Query generated by the Huggin Face model = { sql_query: SELECT ... FROM ... WHERE ... }
"""
@app.post("/gemini/translate/")
async def call_gemini_model(input_data: QueryInput):
    try:
       nl_query = input_data.query
       db_schema = db.get_db_schema()
       selected_language = await get_language()
       if selected_language.get('language') == "Español":
           translator = TranslateLanguage()
           nl_query = translator.translate_to_english(nl_query)
       gemini_model = GoogleModel()
       response = gemini_model.call_SQL_asistant(NL_query=nl_query,schema=db_schema)
       return {"sql_query": parse_gemini_response(response)}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")

"""
This endpoint execute the SQL query generated by the Google Gemini model
Params: input_data = Natural language query
Return: Json with the results of the SQL query generated by Google Gemini model from the natural language query
        {query_result: [(result_1_column_1_value, ..., result_1_column_n_value), ..., (result_n_column_1_value, ..., result_n_column_n_value)]}
"""
@app.post("/gemini/execute_query/")
async def execute_gemini_query(input_data:QueryInput):
    try:
       sql_query = await call_gemini_model(input_data=input_data)
       #db = DBConnection()
       db.generate_db_connection()
       cursor = db.get_db_cursor()
       cursor.execute(f"""
           {sql_query.get('sql_query')}
        """)
       query_result = cursor.fetchall()
       db.quit_db_connection()
       return {"query_result": query_result, "columns": identify_columns_in_query(sql_query.get('sql_query'))}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")

"""
This endpoint returns the parsed database schema
"""
@app.get("/schema/")
def get_schema():
    try:
        return {"schema": db_schema, "real_schema": db.get_db_schema()}
    except Exception as e:
        return {"An error was ocurred": f"{e}" }

"""
This endpoint returns the total input tokens quantity 
input natural language query and database schema
"""
@app.get("/tokens_quantity/")
async def get_tokens_quantity():
    try:
        nl_query = "some nl query"
        input_text = " ".join(["Question: ",nl_query, "Schema:", db_schema])
        init_model = HuggingFaceModel()
        model_inputs = init_model.count_tokens(input_text)
        return {"tokens_quantity": model_inputs}
    except Exception as e:
        return {"An error was ocurred": f"error {e}"}


"""
"""
@app.post("/select_language/")
async def set_language(language: LanguageInput):
    configurated_language.set_language(language.language)
    return { "message": "You has been set your language" }

"""
"""
@app.get("/get_language/")
async def get_language():
    return configurated_language.get_config_language()

@app.post("/number_tokens")
async def get_number_tokens(input_data: TokensInput):
    return { "number_of_tokens": count_tokens_in_string(input_data.query, input_data.db_schema) }


@app.post("/translate_schema/")
async def test_translate_to_sql(input_data: TokensInput):
    try:
        selected_language = await get_language()
        if selected_language.get('language') == "Español":
            nl_query = input_data.query
            translator = TranslateLanguage()
            translated_nl_query = translator.translate_to_english(input_data.query)
            input_text = " ".join(["Question: ",translated_nl_query, "Schema:", input_data.db_schema])
        else:
            nl_query = input_data.query
            input_text = " ".join(["Question: ",input_data.query, "Schema:", input_data.db_schema])
        init_model = HuggingFaceModel()
        response = init_model.call_translate_model(input_text=input_text)
        return {"sql_query": response, "columns": identify_columns_in_query(response)}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")
    
@app.post("/gemini_translate_schema/")
async def test_gemini_translate(input_data: TokensInput):
    try:
       nl_query = input_data.query
       selected_language = await get_language()
       if selected_language.get('language') == "Español":
           translator = TranslateLanguage()
           nl_query = translator.translate_to_english(nl_query)
       gemini_model = GoogleModel()
       response = gemini_model.call_SQL_asistant(NL_query=nl_query,schema=input_data.db_schema)
       return {"sql_query": parse_gemini_response(response)}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"An error was ocurred: {e}")

@app.post("/generate_db_connection/")
async def generate_db_connection(input_data: DBInput):
    try:
        db_name = input_data.db_name
        db_user = input_data.db_user
        db_password = input_data.db_password
        db_host = input_data.db_host
        db.set_db_params(db_host=db_host, db_name=db_name, db_user=db_user, db_password=db_password)
        db.generate_db_connection()
        db_schema = parse_schema(db_host=db_host, db_name=db_name, db_user=db_user, db_password=db_password)
        db.set_db_schema(db_schema=db_schema)
        print("schema: ", db.get_db_schema())
        return {"message": "DB connection generated"}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Error generating DB connection: {e}")