"""adding creation date in user_db models

Revision ID: 2cf0f0d54893
Revises: dbb116a77309
Create Date: 2025-09-22 21:11:56.677656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf0f0d54893'
down_revision: Union[str, Sequence[str], None] = 'dbb116a77309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('crated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'crated_at')
    # ### end Alembic commands ###
