"""add is_superuser to users model

Revision ID: 2e044664d890
Revises: 
Create Date: 2025-09-18 22:04:24.881592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e044664d890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
