"""adding encrypted password field in userbd model

Revision ID: d463fab06b8e
Revises: 32bf2911e019
Create Date: 2025-09-24 23:38:49.947738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd463fab06b8e'
down_revision: Union[str, Sequence[str], None] = '32bf2911e019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('encrypted_password', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'encrypted_password')
    # ### end Alembic commands ###
