"""set ai_model performance with nullable and defaul 0.0

Revision ID: dbb116a77309
Revises: e5a61dc8271e
Create Date: 2025-09-19 16:58:19.064562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb116a77309'
down_revision: Union[str, Sequence[str], None] = 'e5a61dc8271e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
