"""cascade deletes on app models

Revision ID: e5a61dc8271e
Revises: 2e044664d890
Create Date: 2025-09-18 22:09:57.704228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a61dc8271e'
down_revision: Union[str, Sequence[str], None] = '2e044664d890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('query_user_db_id_fkey'), 'query', type_='foreignkey')
    op.drop_constraint(op.f('query_ai_model_id_fkey'), 'query', type_='foreignkey')
    op.drop_constraint(op.f('query_user_id_fkey'), 'query', type_='foreignkey')
    op.create_foreign_key(None, 'query', 'ai_model', ['ai_model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'query', 'user_db', ['user_db_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'query', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_db_user_id_fkey'), 'user_db', type_='foreignkey')
    op.create_foreign_key(None, 'user_db', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_db', type_='foreignkey')
    op.create_foreign_key(op.f('user_db_user_id_fkey'), 'user_db', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.create_foreign_key(op.f('query_user_id_fkey'), 'query', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('query_ai_model_id_fkey'), 'query', 'ai_model', ['ai_model_id'], ['id'])
    op.create_foreign_key(op.f('query_user_db_id_fkey'), 'query', 'user_db', ['user_db_id'], ['id'])
    # ### end Alembic commands ###
