from ai_models import GoogleModel, HuggingFaceModel
from language_config import LanguageConfig
from translate_language import TranslateLanguage
from utils import parse_gemini_response

configurated_language = LanguageConfig()

async def call_gemini_model(nl_query, db_schema):
    try:
       selected_language = configurated_language.get_config_language()
       if selected_language.get('language') == "Español":
           translator = TranslateLanguage()
           nl_query = translator.translate_to_english(nl_query)
       gemini_model = GoogleModel()
       response = gemini_model.call_SQL_asistant(NL_query=nl_query,schema=db_schema)
       return {"sql_query": parse_gemini_response(response)}
    except Exception as e:
        return {"sql_query": None, "error":f"{e}"}
    
    
"""
This endpoint calls to Huggin Face model and return the query in SQL sintax
Params: input_data = Natural language query
Return: Json with the SQL Query generated by the Huggin Face model = { sql_query: SELECT ... FROM ... WHERE ... }
"""
async def translate_to_sql(nl_query, db_schema):
    try:
        selected_language = configurated_language.get_config_language()
        if selected_language.get('language') == "Español":
            translator = TranslateLanguage()
            translated_nl_query = translator.translate_to_english(nl_query)
            input_text = " ".join(["Question: ",translated_nl_query, "Schema:", db_schema])
        else:
            input_text = " ".join(["Question: ",nl_query, "Schema:", db_schema])
        init_model = HuggingFaceModel()
        #print("input text: ", input_text)
        response = init_model.call_translate_model(input_text=input_text)
        return {"sql_query": response}
    except Exception as e:
        return {"sql_query": None, "error" :f"{e}"}